### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset.SliceLoader'

### ISSUE THREAD

**Issue by TPDeramus** [xhu248/AutoSAM#9]
Hi.

I'm attempting to make a `conda` environment of the workflow, but I keep getting the following error thrown whenever I try to run `scripts/main_autosam_seg.py -h` to test the dependencies:

```
(autoSAM) [user@serverID AutoSAM]$ python scripts/main_autosam_seg.py -h
Traceback (most recent call last):
  File "/home/user/Gits/AutoSAM/scripts/main_autosam_seg.py", line 35, in <module>
    from dataset import generate_dataset, generate_test_loader
  File "/home/user/Gits/AutoSAM/dataset/__init__.py", line 3, in <module>
    from .utils import *
  File "/home/user/Gits/AutoSAM/dataset/utils.py", line 5, in <module>
    from dataset.SliceLoader import SliceDataset
ModuleNotFoundError: No module named 'dataset.SliceLoader'
```

I am pretty sure this is an error caused by `torchvision` not importing correctly but I'm not sure why.

This is the current environment setup called via `pip freeze`:
```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1695154477682/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1701099480001/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
alabaster==0.7.13
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1691763562544/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
Babel==2.14.0
batchgenerators==0.25
blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1698890160476/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1695989787169/work
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1698197297464/work
certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1700303426725/work/certifi
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1696001742886/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1698833585322/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1692311806742/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1701563206001/work
docopt==0.6.2
docutils==0.20.1
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1698714947081/work
fire==0.5.0
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1702645466206/work
future==0.18.3
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808679441/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1702091584611/work
google-auth-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/google-auth-oauthlib_1702414855226/work
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpc-split_1701332290556/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1701026962277/work
imageio==2.33.1
imagesize==1.4.1
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1703269254275/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1699364556997/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1691577114857/work
lazy_loader==0.3
linecache2==1.0.0
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1698797478597/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1695367432301/work
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1696716066079/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1698504735452/work
nibabel @ file:///home/conda/feedstock_root/build_artifacts/nibabel_1702339005637/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1700874473373/work/dist/numpy-1.26.2-cp39-cp39-linux_x86_64.whl#sha256=e3c50f65f8bb973822c70baf0e6561ee0aee5b01a3c44246aaa7dfb9f339b29b
numpydoc==1.6.0
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1666056362788/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1697423630459/work
protobuf==4.24.4
pyasn1 @ file:///home/conda/feedstock_root/build_artifacts/pyasn1_1701287008248/work
pyasn1-modules @ file:///home/conda/feedstock_root/build_artifacts/pyasn1-modules_1695107857548/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydicom @ file:///home/conda/feedstock_root/build_artifacts/pydicom_1702744017281/work
Pygments==2.17.2
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1689721553971/work
pykwalify @ file:///home/conda/feedstock_root/build_artifacts/pykwalify_1701902997340/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1698795453264/work
pyradiomics==3.0.1a1
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1695567547297/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1695373447169/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1643557462909/work
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1658328885051/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1699007328119/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1695996823774/work
scikit-image==0.22.0
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1701932004447/work
SciPy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1700812470264/work/dist/scipy-1.11.4-cp39-cp39-linux_x86_64.whl#sha256=3d6a93d72021449625220036943a0939b8292ec74f14a59dca78c8ae60a37dd8
-e git+https://github.com/xhu248/AutoSAM.git@50a6ff44492bedcdb9df749a3bf7b0454c02fe0d#egg=segment_anything
SimpleITK @ file:///home/conda/feedstock_root/build_artifacts/simpleitk_1701806154816/work/build
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
skorch @ file:///home/conda/feedstock_root/build_artifacts/skorch_1693989561015/work
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1684180540116/work
tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1665138452165/work
tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1699025239851/work/tensorboard-2.15.1-py3-none-any.whl#sha256=c46c1d1cf13a458c429868a78b2531d8ff5f682058d69ec0840b0bc7a38f1c0f
tensorboard-data-server @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-data-server_1695425348895/work/tensorboard_data_server-0.7.0-py3-none-manylinux2014_x86_64.whl#sha256=c3327dfe496d955cacc10e4977436bc235dece0c0640c862ede133f2fd842b28
termcolor==2.4.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1689261241048/work
tifffile==2023.12.9
tomli==2.0.1
torch==2.1.2
torchaudio==2.1.2
torchvision==0.16.2
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1691671248568/work
traceback2==1.4.0
trimesh @ file:///home/conda/feedstock_root/build_artifacts/trimesh_1703303188097/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1702176139754/work
unittest2==1.1.0
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1699933488691/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1698235201373/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1701168566739/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work
```
Any suggestions as to what might be the issue here would be appreciated.

**Comment by wm-Githuber** [comment]
> Hi.
> 
> I'm attempting to make a `conda` environment of the workflow, but I keep getting the following error thrown whenever I try to run `scripts/main_autosam_seg.py -h` to test the dependencies:
> 
> ```
> (autoSAM) [user@serverID AutoSAM]$ python scripts/main_autosam_seg.py -h
> Traceback (most recent call last):
>   File "/home/user/Gits/AutoSAM/scripts/main_autosam_seg.py", line 35, in <module>
>     from dataset import generate_dataset, generate_test_loader
>   File "/home/user/Gits/AutoSAM/dataset/__init__.py", line 3, in <module>
>     from .utils import *
>   File "/home/user/Gits/AutoSAM/dataset/utils.py", line 5, in <module>
>     from dataset.SliceLoader import SliceDataset
> ModuleNotFoundError: No module named 'dataset.SliceLoader'
> ```
> 
> I am pretty sure this is an error caused by `torchvision` not importing correctly but I'm not sure why.
> 
> This is the current environment setup called via `pip freeze`:
> 
> ```
> absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1695154477682/work
> aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1701099480001/work
> aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
> alabaster==0.7.13
> async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1691763562544/work
> attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
> Babel==2.14.0
> batchgenerators==0.25
> blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1698890160476/work
> Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1695989787169/work
> cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1698197297464/work
> certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1700303426725/work/certifi
> cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1696001742886/work
> charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1698833585322/work
> click @ file:///home/conda/feedstock_root/build_artifacts/click_1692311806742/work
> colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
> cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1701563206001/work
> docopt==0.6.2
> docutils==0.20.1
> filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1698714947081/work
> fire==0.5.0
> frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1702645466206/work
> future==0.18.3
> gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808679441/work
> google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1702091584611/work
> google-auth-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/google-auth-oauthlib_1702414855226/work
> grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpc-split_1701332290556/work
> idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1701026962277/work
> imageio==2.33.1
> imagesize==1.4.1
> importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1703269254275/work
> importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1699364556997/work
> Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
> joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1691577114857/work
> lazy_loader==0.3
> linecache2==1.0.0
> Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1698797478597/work
> MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1695367432301/work
> mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
> multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1696716066079/work
> networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1698504735452/work
> nibabel @ file:///home/conda/feedstock_root/build_artifacts/nibabel_1702339005637/work
> numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1700874473373/work/dist/numpy-1.26.2-cp39-cp39-linux_x86_64.whl#sha256=e3c50f65f8bb973822c70baf0e6561ee0aee5b01a3c44246aaa7dfb9f339b29b
> numpydoc==1.6.0
> oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1666056362788/work
> packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
> Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1697423630459/work
> protobuf==4.24.4
> pyasn1 @ file:///home/conda/feedstock_root/build_artifacts/pyasn1_1701287008248/work
> pyasn1-modules @ file:///home/conda/feedstock_root/build_artifacts/pyasn1-modules_1695107857548/work
> pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
> pydicom @ file:///home/conda/feedstock_root/build_artifacts/pydicom_1702744017281/work
> Pygments==2.17.2
> PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1689721553971/work
> pykwalify @ file:///home/conda/feedstock_root/build_artifacts/pykwalify_1701902997340/work
> pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1698795453264/work
> pyradiomics==3.0.1a1
> PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
> python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
> pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
> PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1695567547297/work
> PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1695373447169/work
> requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
> requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1643557462909/work
> rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1658328885051/work
> ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1699007328119/work
> ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1695996823774/work
> scikit-image==0.22.0
> scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1701932004447/work
> SciPy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1700812470264/work/dist/scipy-1.11.4-cp39-cp39-linux_x86_64.whl#sha256=3d6a93d72021449625220036943a0939b8292ec74f14a59dca78c8ae60a37dd8
> -e git+https://github.com/xhu248/AutoSAM.git@50a6ff44492bedcdb9df749a3bf7b0454c02fe0d#egg=segment_anything
> SimpleITK @ file:///home/conda/feedstock_root/build_artifacts/simpleitk_1701806154816/work/build
> six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
> skorch @ file:///home/conda/feedstock_root/build_artifacts/skorch_1693989561015/work
> snowballstemmer==2.2.0
> Sphinx==7.2.6
> sphinxcontrib-applehelp==1.0.7
> sphinxcontrib-devhelp==1.0.5
> sphinxcontrib-htmlhelp==2.0.4
> sphinxcontrib-jsmath==1.0.1
> sphinxcontrib-qthelp==1.0.6
> sphinxcontrib-serializinghtml==1.1.9
> sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1684180540116/work
> tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1665138452165/work
> tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1699025239851/work/tensorboard-2.15.1-py3-none-any.whl#sha256=c46c1d1cf13a458c429868a78b2531d8ff5f682058d69ec0840b0bc7a38f1c0f
> tensorboard-data-server @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-data-server_1695425348895/work/tensorboard_data_server-0.7.0-py3-none-manylinux2014_x86_64.whl#sha256=c3327dfe496d955cacc10e4977436bc235dece0c0640c862ede133f2fd842b28
> termcolor==2.4.0
> threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1689261241048/work
> tifffile==2023.12.9
> tomli==2.0.1
> torch==2.1.2
> torchaudio==2.1.2
> torchvision==0.16.2
> tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1691671248568/work
> traceback2==1.4.0
> trimesh @ file:///home/conda/feedstock_root/build_artifacts/trimesh_1703303188097/work
> typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1702176139754/work
> unittest2==1.1.0
> urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1699933488691/work
> Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1698235201373/work
> yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1701168566739/work
> zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work
> ```
> 
> Any suggestions as to what might be the issue here would be appreciated.

Hello, have you solved the problem? I have the same problem as you, please.

**Comment by liyihao76** [comment]
The dataset.SliceLoader in the source code is not used at all, just comment out the 5th line of code in ./dataset/utils.py
源码中dataset.SliceLoader根本用不到，注释掉./dataset/utils.py第5行代码即可
